### ISSUE TITLE
Oresheep conflict

### ISSUE THREAD

**Issue by matthewm2148** [Icedice9/OreSheep#5]
mod conflict with miniheads it stops at the world building screen and crashes

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CorePlugin (ForgeEndertech-1.12.1-4.3.1.0-build.0071.jar)
  FarseekCoreMod (Farseek-1.12-2.2.3.jar)
  DLFMLCorePlugin (DynamicLights-1.12.1.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  BetterSprintingCore (BetterSprinting++MC-1.12.2++v2.1.0.jar)
  BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
  SRM-Core (secretroomsmod-1.12.2-5.2.7.jar)
  FMLPlugin (elulib-0.1.11.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  BCModPlugin (backpacks+1.12.2+-+3.4.3.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  CreativePatchingLoader (CreativeCore+v1.9.16+mc1.12.2.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  LittlePatchingLoader (LittleTiles+v1.5.0-pre71+mc1.12.2.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  BedPatch (bedpatch-2.0-1.12.2.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  Wizardry Plugin (wizardry-0.7.2.jar)
  LoadingPlugin (AdChimneys-1.12.1-3.2.1.2-build.0079.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  SoundFixPatchingLoader (AmbientSounds+v2.2.2+mc1.12.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.7.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 2/16/18 1:41 PM
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block miniheads:store-display, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:235)
	at com.snatchybuckles.miniheads.block.StoreDisplayBlock.func_176203_a(StoreDisplayBlock.java:56)
	at oresheepmod.OreRegistryDraw.addAllSubBlocks(OreRegistryDraw.java:673)
	at oresheepmod.OreRegistryDraw.getAllOres(OreRegistryDraw.java:345)
	at oresheepmod.OreRegistryDraw.readConfig(OreRegistryDraw.java:166)
	at oresheepmod.OreSheepEventHandler.onWorldLoad(OreSheepEventHandler.java:63)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1729_OreSheepEventHandler_onWorldLoad_Load.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.call(Reflector.java:943)
	at Reflector.postForgeBusEvent(Reflector.java:1170)
	at Reflector.postForgeBusEvent(Reflector.java:1156)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:113)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:209)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)

**Comment by mattcloward** [comment]
Working on a fix! Thanks for the bug report!

**Comment by mattcloward** [comment]
Fixed in version 4.0.2!
